version: '3.7'
services:

  postgresql:
    image: postgres:11.4-alpine
    environment:
      POSTGRES_USER: sample_project
      POSTGRES_PASSWORD: protected_password
      POSTGRES_DB: sample_project_development

    ports:
      - 5632:5432
